<?php

$title = 'Add new employee';
$this->headTitle($title);

$form->setAttribute('action', $this->url('employee', array('action' => 'add') ) );
$form->prepare();
?>

<style>
form {
    
}
form > div{
    
}
</style>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php echo $this->form()->openTag($form); ?>
    <div><?php echo $this->formHidden($form->get('id') ); ?></div>
    <div><?php echo $this->formRow($form->get('firstname') ); ?></div>
    <div><?php echo $this->formRow($form->get('lastname') ); ?></div>
    <div><?php echo $this->formRow($form->get('birthdate') ); ?></div>
    <div><?php echo $this->formSubmit($form->get('submit') ); ?></div>
<?php echo $this->form()->closeTag(); ?>
