-- MySQL Script generated by MySQL Workbench
-- Sat 05 Dec 2015 07:02:05 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema myworkdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myworkdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myworkdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `myworkdb` ;

-- -----------------------------------------------------
-- Table `employers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employers` ;

CREATE TABLE IF NOT EXISTS `employers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(25) NULL,
  `lastname` VARCHAR(30) NULL,
  `birthdate` DATE NULL,
  `date_created` DATETIME NOT NULL DEFAULT NOW(),
  `date_modified` DATETIME NOT NULL DEFAULT NOW(),
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `task_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `task_types` ;

CREATE TABLE IF NOT EXISTS `task_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NULL,
  `description` VARCHAR(255) NULL,
  `date_created` DATETIME NOT NULL DEFAULT NOW(),
  `date_modified` DATETIME NOT NULL DEFAULT NOW(),
  `status` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tasks` ;

CREATE TABLE IF NOT EXISTS `tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_type_id` INT UNSIGNED NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(90) NULL,
  `description` TEXT NULL,
  `date_created` DATETIME NOT NULL DEFAULT NOW(),
  `date_modified` DATETIME NOT NULL DEFAULT NOW(),
  `status` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_task_employee_idx` (`employee_id` ASC),
  INDEX `fk_task_task_type1_idx` (`task_type_id` ASC),
  CONSTRAINT `fk_task_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `employers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_task_type1`
    FOREIGN KEY (`task_type_id`)
    REFERENCES `task_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
